

GET  http://www.omdbapi.com/?apikey=ca90f062&s=Robin%20Hood:%20Men%20in%20Tights HTTP/1.1

###

GET  http://www.omdbapi.com/?apikey=ca90f062&t=tt0360717 HTTP/1.1

###

GET  http://www.omdbapi.com/?apikey=ca90f062&i=tt0110357 HTTP/1.1

###

GET  http://www.omdbapi.com/?apikey=ca90f062&t=terminator HTTP/1.1

###
